apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: pcjoshidotnetdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pcjoshidotnetdocker 
    spec:
      containers:
        - name: pcjoshidotnetdocker 
          image: rlincregistry.azurecr.io/pcjoshidotnetdocker
          ports:
          - containerPort: 80